version: '2'
services:
  testmono02-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/testmono02/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testmono02
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
